### ISSUE TITLE
기여 목록 정리

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#11]
각자 프로젝트에 기여한 활동들은 Wiki의 기타 기여 목록, 코드 기여 목록, 번역 기여 목록에 간단히 적어주세요. 
해당 기여를 좀 더 자세히 설명하고 싶으면 Pull Request를 통해 github page에 post를 추가해주시기 바랍니다.

**Comment by chyeon** [comment]
넵 알겠습니다!
