### ISSUE TITLE
변역 기여 방법 질문드립니다.

### ISSUE THREAD

**Issue by chyeon** [19-1-skku-oss/2019-1-OSS-L4#12]
저희가 commit한 번역을 mattermost프로젝트에 어떻게 기여하는게 좋을까요...?

**Comment by JTzzang** [comment]
Mattermost 공식 번역 서버https://translate.mattermost.com 에서 i18n 진행 현황을 보고 참여할 수 있습니다.

**Comment by chyeon** [comment]
오오 감사합니다!!

**Comment by woolimcho** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L4/pull/14 를 참고해주세요.
