### ISSUE TITLE
License 설정

### ISSUE THREAD

**Issue by JTzzang** [19-1-skku-oss/2019-1-OSS-L4#13]
#저희 프로젝트 license 설정이 필요한가요??

**Comment by woolimcho** [comment]
Mattermost의 경우 세부 프로젝트마다 GPL, Apache 2.0 등 다른 라이센스를 혼용하고 있긴 한데, 소스 코드를 공개 할 경우 각 라이센스의 요구 조건을 충족하게 됩니다.
저희 프로젝트의 경우에는 사실 해당 repository를 직접 fork한 것이 아니라 해당 코드를 그대로 들고와서 기록용으로 사용하는 것이기 때문에 라이센스 설정을 하기 보다는 Mattermost의 방침을 따른다고 언급하는 방향이 좋을 것 같습니다.

**Comment by JTzzang** [comment]
그렇군요. 좋은 답변 감사드립니다.
