### ISSUE TITLE
mattermost 기여에 대한 가이드를 정리하여 올리고 싶은데 어디에 올리면 될까요?

### ISSUE THREAD

**Issue by JTzzang** [19-1-skku-oss/2019-1-OSS-L4#15]
분량이 많아 정리를 함께 도와서 해주실 분도 있으면 좋겠습니다!

**Comment by woolimcho** [comment]
저희 깃허브 페이지에 올려주시면 될 것 같습니다. https://developers.mattermost.com/contribute/getting-started/ 참고해서 작성해주세요!

**Comment by chyeon** [comment]
저도 같이 참여하겠습니다!
