### ISSUE TITLE
깃허브 페이지 버그 수정

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#18]
현재 저희 깃허브 페이지에 들어갈 경우 멤버 -> View Posts가 작동이 되지 않습니다. 
https://github.com/19-1-skku-oss/2019-1-OSS-L4/blob/gh-pages/_pages/author-woolim.html
이 파일처럼 author-(자기 이름 코드).html 로 파일을 만들고, author-woolim.html을 참고하여 자신의 정보에 맞게 바꿔주세요.
자기 이름 코드는 View Posts를 누를 경우 url에서 author-(자기 이름 코드)로 확인하실 수 있습니다.

@kim95175  @choys0401  @JTzzang  @chyeon

**Comment by chyeon** [comment]
수정 후 확인했습니다!

**Comment by kim95175** [comment]
확인했습니다! 수정 완료

**Comment by choys0401** [comment]
확인 후 수정했습니다.

**Comment by JTzzang** [comment]
확인하고 수정하여 pr 날렸습니다.
