### ISSUE TITLE
번역 현황 게시

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#19]
Mattermost 프로젝트에 현재 번역이 어색한게 많아서, 수정 전과 수정 후를 보여 줄 수 있는 게시글이 있으면 좋을 것 같습니다!
해야 할 일은 아래 3가지 입니다.
- 번역 수정 전 어색한 부분 스크린샷 포함 설명
- 번역 수정 후 스크린샷 포함 설명
- Translation 서버에 적용한 번역이 어떻게 프로젝트에 적용되는지 (일정 주기마다 Sync, Translation PR 스크린샷 포함)

번역 관련 분이 맡아주셨으면 좋겠습니다.

**Comment by JTzzang** [comment]
확인했습니다. 토요일까지 진행하겠습니다.

**Comment by woolimcho** [comment]
> 확인했습니다. 토요일까지 진행하겠습니다.

번역 전/후 적용 스크린샷 등 자료가 필요하면 이슈를 만들어서 요청해 주세요.

**Comment by woolimcho** [comment]
게시글 등록 완료
