### ISSUE TITLE
코드 PR 현황 게시

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#20]
@kim95175 https://github.com/mattermost/mattermost-server/pull/11000 PR이 머지되었는데, 해당 PR의 내용, 그리고 코드 리뷰 과정등을 상세하게 기록해주시면 좋을 것 같습니다!

**Comment by kim95175** [comment]
확인했습니다! 토요일까지 올리겠습니다

**Comment by woolimcho** [comment]
> 확인했습니다! 토요일까지 올리겠습니다

제꺼 중에서 Migrate 관련 3개 포함해서 Migrate 관련 4개 PR 전부 부탁드립니다

**Comment by jkl5616** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L4/pull/26#issue-286080789
