### ISSUE TITLE
Team Page Posts 카테고리 정리

### ISSUE THREAD

**Issue by kim95175** [19-1-skku-oss/2019-1-OSS-L4#25]
현재 저희 팀 페이지의 post 카테고리가 다음과 같이 되어있는데, 겹치는 부분이 있는 만큼
카테고리 종류를 확정하고 이에 따라 각 포스트의 카테고리를 수정하는 작업을 진행하는 것이 좋다고 생각합니다.
이에 대한 의견을 달아주시고 의견을 통해 카테고리가 확정이 되면 각자 수정해 주시면 될 것 같습니다.

![image](https://user-images.githubusercontent.com/43230681/59085041-43317780-8938-11e9-8ca5-cb5a33ba58b1.png)

**Comment by woolimcho** [comment]
제 생각엔 MatterMost 카테고리는 없애고, Pull Request도 사실 각 Contribution에 포함되는거니 각 Contribution 혹은 Contribution Guideline에 포함하는 식으로 하면 될 것 같습니다.

**Comment by JTzzang** [comment]
Contribution Guideline 카테고리를 위쪽으로 올리는 것은 어떤가요?
