### ISSUE TITLE
MatterMost CLA 작성

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#3]
Mattermost 프로젝트에 Contribution 하기 전에, Contributor Agreement를 작성해 주셔야 합니다.
[https://www.mattermost.org/mattermost-contributor-agreement/](https://www.mattermost.org/mattermost-contributor-agreement/)

작성한 후 [link](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true)에서 Approved Contributor 등록되었는지 확인하시고, [Developer Guide](https://developers.mattermost.com/contribute/server/) 를 참고하셔서 환경을 설정해 주세요.

**Comment by kim95175** [comment]
김승현 작성 완료했습니다

**Comment by choys0401** [comment]
작성 완료!

**Comment by chyeon** [comment]
이채현 작성했습니다

**Comment by JTzzang** [comment]
김준태 작성 완료했습니다
