### ISSUE TITLE
번역 전/후 스크린샷 자료 요청

### ISSUE THREAD

**Issue by chyeon** [19-1-skku-oss/2019-1-OSS-L4#30]
변역 현황 게시글 및 위키 작성을 위한 스크린샷 자료 있으시다면 부탁드립니다..!

**Comment by woolimcho** [comment]
어떤 부분이 필요한지 구체적으로 부탁드립니다.

**Comment by chyeon** [comment]
모바일 앱 시작 화면에 나오는 "연결" 부분을 번역 서버에서 바꿨었는데 번역 후 상황을 어떻게 찾을 지 모르겠습니다...

**Comment by woolimcho** [comment]
![KakaoTalk_Photo_2019-06-09-20-33-23](https://user-images.githubusercontent.com/2460345/59158486-d6fc7280-8af5-11e9-9207-a0972ee09f18.jpeg)
![KakaoTalk_Photo_2019-06-09-20-33-20](https://user-images.githubusercontent.com/2460345/59158487-d82d9f80-8af5-11e9-8e25-4fc57be6ffa7.jpeg)

**Comment by woolimcho** [comment]
요청하신 자료입니다.

**Comment by chyeon** [comment]
감사합니다!!
