### ISSUE TITLE
wiki 홈

### ISSUE THREAD

**Issue by JTzzang** [19-1-skku-oss/2019-1-OSS-L4#31]
wiki 홈에도 저희 팀의 프로젝트나 팀원소개가 있으면 좋겠는데 어떤 사항들이 있으면 좋을까요? #

**Comment by chyeon** [comment]
wiki 카테고리에 mattermost 프로젝트 소개 항목을 추가 할까요??

**Comment by choys0401** [comment]
https://translate.mattermost.com 통계 올리는것도 좋을 것 같네요
