### ISSUE TITLE
팀 github page

### ISSUE THREAD

**Issue by JTzzang** [19-1-skku-oss/2019-1-OSS-L4#32]
저희 팀 github 페이지에서 특정 카테고리를 누르면, 해당 카테고리가 아닌 전체 카테고리가 뜨는데 이 부분을 바꿀 수는 없을까요?

**Comment by woolimcho** [comment]
https://github.com/19-1-skku-oss/2019-1-OSS-L4/commit/e213432301810f1fdb5479caacc2d3fd30e138bd

**Comment by woolimcho** [comment]
해당 커밋으로 해결했습니다.

**Comment by JTzzang** [comment]
수고하셨습니다. 감사합니다.
