### ISSUE TITLE
발표 순서 및 역할

### ISSUE THREAD

**Issue by kim95175** [19-1-skku-oss/2019-1-OSS-L4#33]
11일 발표에 대비해 순서 및 구성을 정해야 할 것 같습니다.

일단 대략적인 제 생각은

1. Mattermost 소개, 개관 - 김승현
2. Code contribution - 조우림
3. 번역 Contribution - 김준태

요정도로 생각중인데 자기가 발표하고 싶은 부분이 있다, 이런 내용이 들어갔으면 좋겠다 등
추가의견 있으시면 덧글 달아주세요.

**Comment by JTzzang** [comment]
좋을 것 같습니다. 맞춰서 준비하겠습니다.
