### ISSUE TITLE
오늘 활동 내용 작성

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#5]
팀 깃허브 페이지에 오늘 활동 내용(5.28)을 작성해 주실 분이 있으시면 좋을 것 같습니다.

**Comment by kim95175** [comment]
할분 없으면 제가 하겠습니다.

**Comment by woolimcho** [comment]
@kim95175 넵 알겠습니다.

**Comment by kim95175** [comment]
@jkl5616  업로드 완료 했습니다. 시간 관계상 바로 commit 했습니다.
