### ISSUE TITLE
번역 관련 글 작성 필요

### ISSUE THREAD

**Issue by woolimcho** [19-1-skku-oss/2019-1-OSS-L4#7]
Mattermost 번역에 어떻게 참여하는지 글이 있으면 좋을 것 같습니다! 
번역을 담당하시는 팀원분이 하시면 좋을 것 같습니다.

**Comment by JTzzang** [comment]
제가 해보겠습니다!

**Comment by woolimcho** [comment]
@JTzzang 네 부탁드립니다!

**Comment by woolimcho** [comment]
@JTzzang 이번주 수업 전까지 작성 부탁드립니다

**Comment by JTzzang** [comment]
네 알겠습니다.

**Comment by JTzzang** [comment]
작성하여 pull request 하였습니다.

**Comment by woolimcho** [comment]
@JTzzang 수고하셨습니다.
